server:
  port: 80

spring:
  datasource:
    url: jdbc:postgresql://raja.ccvpmnflk8mv.ap-south-1.rds.amazonaws.com:5432/raja
    username: postgres
    password: Raja$241
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL81Dialect