server:
  port: 80

spring:
  datasource:
    url: jdbc:sqlserver://raja-dev.database.windows.net:1433;database=raja
    username: raja@raja-dev
    password: Evoke@123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.SQLServerDialect