server:
  port: 80
spring:
  datasource:
    url: jdbc:sqlserver://dev-raja.database.windows.net:1433;database=dev
    username: raja
    password: Evoke@123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.SQLServerDialect